// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMessages():Promise<Array<main.SimpleMessage>>;

export function GetUserOptions():Promise<main.UserOptions>;

export function SaveUserOptions(arg1:main.UserOptions):Promise<void>;
