// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetUserOptions() {
  return window['go']['main']['App']['GetUserOptions']();
}

export function SaveUserOptions(arg1) {
  return window['go']['main']['App']['SaveUserOptions'](arg1);
}
